# Intel NPU Shader 2
# NPU-forward Iris shaderpack variant for the NPU XMX bridge prototype.

customTexture.npuAssist=npu_xmx_bridge:shader_preview
oldLighting=false
shadow.culling=false
blend.gbuffers_water.colortex4=off
blend.gbuffers_water.colortex1=off
blend.gbuffers_water.colortex2=off
blend.gbuffers_hand_water.colortex4=off
blend.gbuffers_hand_water.colortex1=off
blend.gbuffers_hand_water.colortex2=off
